name: Deploy to Firebase

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root deps
        run: npm ci

      - name: Build app and copy to functions/.next
        run: npm run build

      - name: Install functions deps and build
        working-directory: functions
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAPONE_29D65 }}"
          channelId: live
          projectId: tapone-29d65
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks